### ISSUE TITLE
打包软件失败求指导

### ISSUE THREAD

**Issue by Feiman55** [Wsine/android_builder#65]
[https://github.com/Feiman55/NoActive.git](url)

**Comment by Wsine** [comment]
没看懂，执行的 Action 在哪里

**Comment by Feiman55** [comment]
我不太懂，刚开始学，我吧我链接里这个项目释放了一段代码，想要在线打包一下，然后就用了你的项目打包，但是每次都提示我1个错误，3个警告

**Comment by Wsine** [comment]
https://github.com/Feiman55/android_builder/actions/workflows/build.yaml

完全没看到运行结果

**Comment by Feiman55** [comment]
这是原作者写的一个xp框架hook插件源代码，我问原作者了，他让我释放一段代码补充一个功能用，让我再打包，我打包不成功了。我不太懂，不过可以确定这个问题和你的项目没关系，你的项目很不错，非常感谢。我不太懂向你咨询一下，还望见谅

**Comment by Feiman55** [comment]
我又重新运行了一下，错误结果还是出来了，我感觉肯定是哪里我搞的不对

**Comment by Feiman55** [comment]
就是你发的这个链接，不忙的话，抽空帮忙看一下哪里的问题吧。新人求指导，没时间的话，你先忙，已经很打扰你了，还望见谅

**Comment by Wsine** [comment]
错误信息为：Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

对应更改 Action 配置文件中的 Java 版本就好

**Comment by Feiman55** [comment]
好，我去摸索摸索怎么搞，身边没电脑，我看看这个怎么处理，非常感谢

**Comment by Feiman55** [comment]
我刚去认真的看了一下你的项目说明，目前像我这个提示Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.它，那我是不是把你项目中的java-version 1.8改你下就行了？它github不是默认的java11环境吗？求指导

**Comment by Feiman55** [comment]
直接把你项目那个文件中的java-version: 1.8  改为  java-version: 11 好像还是不行？我肯定改错了吧

**Comment by Wsine** [comment]
不是的，你需要参考 setup-java 的 action 环境，https://github.com/actions/setup-java

根据你的情况，简单点来说，从那里摘抄相应的代码片段替换就好，直接用17应也行。

**Comment by Feiman55** [comment]
/workflows/build.yaml我直接替换你项目里这个里面的环境吗？我只用手机aide写过简单的软件，初学，不太懂，还望见谅

**Comment by Wsine** [comment]
是的，直接替换，然后重新 trigger 一下 action workflow 试试，注意空格缩进，yml 的格式要求

**Comment by Feiman55** [comment]
我试了好多还是失败，哎，我还是太笨，我是直接复制steps:
- uses: actions/checkout@v3
- uses: actions/setup-java@v3
  with:
    distribution: 'zulu' # See 'Supported distributions' for available options
    java-version: '17'
- run: java HelloWorldApp.java
- 进去替换的你的那一段，还是不行

**Comment by Wsine** [comment]
下面这个是正确的修改。如果你缺少很多关键的知识，不如趁机学习必要的再尝试，盲目尝试效率比较低。

```
name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - id: get-project
        name: Get project name
        run: echo "::set-output name=PROJECT::$(cat project-to-build)"
      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project
      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-build-apk
          path: ./**/*.apk
```
